### ISSUE TITLE
Change the native dependency we use to test if the module is rebuilt

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron-rebuild#113]
Currently we use `nslog` purely to test whether our node_modules are being rebuilt or not.

It might be worth looking into alternatives that install more nicely on more systems.  Or thinking if there is an alternative to having a native dependency in the first place.

I don't have any ideas yet, but I am going to move all "nslog failed to install" issues to this one 👍

**Comment by wojtkowiak** [comment]
Since my team also have problems (as most Windows users) with compiling native packages like `nslog` I can spend some time on this.

Today I was trying to understand the current logic but I got kinda lost.
```javascript
  // Try to load our canary module - if it fails, we know that it's built
  // against a different node module than ours, so we're good
  //
  // NB: Apparently on OS X, this not only fails to be required, it segfaults
  // the process, because lol.
  try {
    let args = ['-e', 'require("nslog")']
    await spawn({cmd: process.execPath, args});

    require('nslog');
  } catch (e) {
    return true;
  }
```
At first we try to run current node with `require('nsolg');`. So if that fails we `return true` which basically indicates that we need to rebuild. Should that be the opposite? The comment seems to be saying that but the code says something else - or am I getting it wrong?

**Comment by malept** [comment]
@MarshallOfSound given the rewrite, I think this can be closed 😄

**Comment by MarshallOfSound** [comment]
👍
