### ISSUE TITLE
Use node-gyp's devdir instead of setting env.HOME

### ISSUE THREAD

**Issue by EdShaw** [electron/electron-rebuild#117]
I've been attempting to use native modules written in Rust with Electron. My Rust distribution is provided by rustup, which stores Rust distributions and configuration in $HOME. When electron-rebuild calls node-gyp, it overwrites the environment's HOME, which causes rustup to fail to find the rust toolchain.

electron-rebuild sets env.HOME to point node-gyp to the correct Node headers, but this not necessary - if we pass the --devdir argument to node-gyp, then node-gyp will pick up Electron's Node headers, rather than the system's, without breaking any tools that depend on $HOME.

Using versions:
Electron: 1.4.3
electron-rebuild: 1.2.1

**Comment by ffflorian** [comment]
Same here! I am building a project based on [`neon`](https://github.com/neon-bindings/neon) and when I run `electron-rebuild` it fails with `error: no default toolchain configured`.

**Comment by malept** [comment]
If this is no longer an issue, this should be closed.

**Comment by EdShaw** [comment]
I haven't tried this recently, so I'm not sure if this is fixed. Have there been improvements to this? If not, then I suspect it's still an issue.

**Comment by malept** [comment]
electron-rebuild got rewritten recently. Do you have a sample Electron app that uses Neon?

**Comment by EdShaw** [comment]
Not handy. I'll set up a simple project to test it now.

**Comment by EdShaw** [comment]
Sorry for the delay.

This is still an issue - electron-rebuild is still clobbering env  HOME.

I'll look at providing a minimal sample app that repros the neon issue. Not sure how useful it will be though - it's pretty easy to see the effect that it has on the env by e.g. logging out home in binding.gyp

**Comment by dherman** [comment]
I've built a little tool called [electron-build-env](https://github.com/dherman/electron-build-env) that works like a subset of the electron-rebuild functionality, mostly as a temporary workaround for lack of electron-rebuild support for neon. But it also demonstrates how you can use `[npm_config_devdir](https://github.com/dherman/electron-build-env/blob/master/index.js#L103)` instead of changing HOME.

If you'd like, I could submit a PR to do the same thing in electron-rebuild, but I probably wouldn't know how to adequately test it. At least it might help show how it could work?

**Comment by MarshallOfSound** [comment]
@dherman 

> If you'd like, I could submit a PR to do the same thing in electron-rebuild

That would be awesome 😄 

As for tests, as long as our current test suite passes I'm 👍
