### ISSUE TITLE
`fsevents` rebuilded on Windows

### ISSUE THREAD

**Issue by wenshiqi0** [electron/electron-rebuild#185]
OS windows 8
Node 7.2.0
Electron-builder 1.5.11

Did electron-rebuild handle `fsevents` rebuilding for Windows? Even I am in Windows, the `fsevents` module may still be rebuilded, and this make errors.

**Comment by MarshallOfSound** [comment]
@wenshiqi0 At no point should `fsevents` be present in the `node_modules` folder on windows.  This was fixed in yarn a while back and NPM has never attempted installed `fsevents` on windows.

If a package manager fails to install a module it should remove any trace of it from the filesystem, if it is still hanging around when we manually traverse the tree how are we supposed to know if it is not a good module to try build or not?
