### ISSUE TITLE
Which options are available for the --arch switch?

### ISSUE THREAD

**Issue by lapagept** [electron/electron-rebuild#290]
Hi there,

I want to rebuild my sqlite3 native module for Windows. But I 'm working on mac.

Which are available options for the --arch switch when using electron-rebuild? Unable to find those options on the web...

Is it possible to rebuild electron native modules for Windows when coding on a Mac?

Please help!

**Comment by Jack-Barry** [comment]
This would be a big help. Using a nonexistent arch is currently not throwing any kind of error to indicate it's not supported.

**Comment by jacobq** [comment]
Also, which is the correct form: `--arch=foo` or `--arch foo` Does it matter?

**Comment by Jack-Barry** [comment]
@jacobq As far as I know the package they are using to parse CLI inputs (`yargs`) knows how to handle both. 

As for this issue, could probably be configured to only accept specific arches here using [choices](https://yargs.js.org/docs/#choices): 

https://github.com/electron/electron-rebuild/blob/367e08129aea4a3099eb49986f90668e39a142e7/src/cli.ts#L22-L23

I just haven't had to deal with this one for a while and don't have time at the moment to make the fix

**Comment by malept** [comment]
It's a little bit more difficult than that, because the officially supported arches varies from version to version, and obviously from platform to platform. There's an entire file in Electron Packager that defines this: https://github.com/electron/electron-packager/blob/v14.2.1/src/targets.js

To answer the original question, it is not currently possible to cross-compile native node modules across platforms, as Node itself does not have that capability.
