### ISSUE TITLE
electron-rebuild does not rebuild module after updating electron to 5.0.2

### ISSUE THREAD

**Issue by stoefln** [electron/electron-rebuild#304]
I previously used electron 3 to run this module: https://github.com/justadudewhohacks/opencv4nodejs 

Besides having troubles packaging for windows everything worked fine.
Now I tried to upgrade to electron 5.0.2 (also tried with 4.2.4) and it seems it's not doing anything, since it exits after a single second.

This is the output:

> Repeato@1.0.0 electron-rebuild /..../Documents/workspace/myapp
> electron-rebuild -w opencv4nodejs
> 
> ✔ Rebuild Complete

Here is the app I am trying to get this working for: https://github.com/stoefln/opencv4nodejs-test

**Comment by malept** [comment]
Try setting your `electron-rebuild` script in `package.json` to:

```
DEBUG=electron-rebuild* electron-rebuild -w opencv4nodejs
```

and then paste the output here when you run it.

**Comment by malept** [comment]
Also, I think one problem is that for some reason you have both `electron` *and* `electron-prebuilt-compile` installed.

I think that you may want to consider redoing your Electron Tooling configuration, because you have a lot of modules installed that overlap. Since you're using Webpack, I would suggest removing all of the Electron tooling modules, install [Electron Forge](https://electronforge.io) with its Webpack plugin, and only use `electron` instead of both that *and* `electron-prebuilt-compile`. As a bonus, `electron-rebuild` comes built-in to Forge.

**Comment by stoefln** [comment]
Thanks very much @malept.
Removing electron-prebuilt-compile fixed my issue! However, I am facing a different one now (app.getAppPath() is pointing to `node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar` now), but I guess the problem is not related to electron-rebuild. 
You can close the ticket I guess...
