### ISSUE TITLE
node-ffi not compatible when Electron bundled with Node >= 12

### ISSUE THREAD

**Issue by denglai** [electron/electron-rebuild#344]
node-version:10.17.0
node-gyp-version:6.0.1
electron--version:7.1.2
window10
errorMsg:
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)

result:   It's been run electron-rebuild.cmd,But there were still errors

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-rebuild with the environment variable `DEBUG=electron-rebuild` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point. **This includes the name and version of the native module you are having problems with.**

**Comment by denglai** [comment]
node-ffi @lastest and "electron": "^7.1.5", Is it incompatible?

**Comment by malept** [comment]
Electron 7 is bundled with Node 12. As of this comment, the `ffi` module has not been updated for Node 12. I would suggest using [`ffi-napi`](https://www.npmjs.com/package/ffi-napi) instead, which has support for Node 12 and is also rebuilt in the `electron-rebuild` testsuite.
